import type { NextPage } from 'next';
import Head from 'next/head';
import { data, someFunc } from '../data';

const Home: NextPage = () => {
	const start = new Date(2021, 0, 1);
	const end = new Date(2021, 5, 1);
	someFunc('GroupName', 'month', start, end, data);
	return (
		<div>
			<Head>
				<title>Assigment</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
		</div>
	);
};

export default Home;
